---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  driver_plugin: digital_ocean
  driver_config:
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

- name: ubuntu-14.04
  driver_plugin: digital_ocean
  driver_config:
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

- name: centos-6.5
  driver_plugin: digital_ocean
  driver_config:
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

- name: centos-5.8
  driver_plugin: digital_ocean
  driver_config:
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

suites:
- name: default
  run_list:
  - recipe[ssh_known_hosts]
  attributes: {}
- name: cacher
  run_list:
  - recipe[ssh_known_hosts::cacher]
  attributes: {}
- name: cacher-client
  run_list:
  - recipe[ssh_known_hosts::default]
  attributes:
    ssh_known_hosts:
      use_data_bag_cache: true
