---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[ssh_known_hosts]
  attributes: {}
- name: cacher
  run_list:
  - recipe[ssh_known_hosts::cacher]
  attributes: {}
- name: cacher-client
  run_list:
  - recipe[ssh_known_hosts::default]
  attributes:
    ssh_known_hosts:
      use_data_bag_cache: true
